### ISSUE TITLE
The "TIBBER_INFLUX_MEASUREMENT" variable is not set. Defaulting to a blank string.

### ISSUE THREAD

**Issue by cjungde** [solectrus/tibber-collector#201]
Ich habe ein komplett neues System auf einem docker (über proxmox) aufgesetzt.
Bisher war nur der MQTT Collector aktiv und das funktioniert auch sehr gut. 

Heute habe ich dann gem der Anleitung von https://docs.solectrus.de/referenz/tibber-collector/konfiguration.html
versucht, den Tibber Collector zu aktivieren und die Log Fehler unten bekommen. Den SENEC Charger habe ich nicht eingerichtet.

Der Tibber Token ist an anderer Stelle erfolgreich im Einsatz und ich habe ihn auch nochmal bei Tibber überprüft.
Brauche ich für den Kontext nicht auch noch die Tibber Home-ID ?

```
root@docker:~/solectrus# docker compose logs tibber-collector
WARN[0000] The "TIBBER_INFLUX_MEASUREMENT" variable is not set. Defaulting to a blank string. 
tibber-collector-1  | Tibber collector for SOLECTRUS, Version 0.2.7, built at 2024-08-30T10:31:40.483Z
tibber-collector-1  | https://github.com/solectrus/tibber-collector
tibber-collector-1  | Copyright (c) 2023-2024 Georg Ledermann, released under the MIT License
tibber-collector-1  | 
tibber-collector-1  | Using Ruby 3.3.4 on platform x86_64-linux-musl
tibber-collector-1  | Pulling from https://api.tibber.com/v1-beta/gql every 3600 seconds
tibber-collector-1  | Pushing to InfluxDB at http://influxdb:8086, bucket solectrus, measurement 
tibber-collector-1  | 
tibber-collector-1  | #1 - 2024-10-31 06:02:59 +0100
tibber-collector-1  |   Fetching prices from Tibber ... Error Context creation failed: invalid token
tibber-collector-1  |   Sleeping for 3600 seconds ...
```

**Comment by ledermann** [comment]
Eines vorweg: Der Tibber-Collector ergibt **derzeitig** nur Sinn, wenn man auch den [SENEC-Charger](https://docs.solectrus.de/referenz/senec-charger/) installiert. Die Preise von Tibber werden in SOLECTRUS noch an keiner anderen Stelle verwendet, auch wenn das für die Zukunft geplant ist.

Aufgrund deines Log-Outputs sehe ich, dass die Doku einen Fehler enthält, die Variable für das Measurement fehlt bzw. hat den falschen Namen, ich habe das gerade [korrigiert](https://github.com/solectrus/docs/commit/8a75d20e360e8b1d332a3ea66c4855607856a0f4). Bitte passe das auch bei dir an.

Es bleibt das Problem mit dem Token. Bitte prüfe mal mit folgendem Befehl, welche Variablen tatsächlich beim Container ankommen:

```bash
docker compose exec tibber-collector env
```

Findet sich da wirklich die Variable `TIBBER_TOKEN` mit dem richtigen Inhalt? Ein korrektes Token sieht etwa so aus: `5K4MVS-OjfWhK_4yrjOlFe1F6kJXPVf7eQYggo8ebAE` (das ist das Demo-Token)

Bezüglich Home-ID: Nach meinem Kenntnisstand ist die nicht notwendig. Oder hast du eventuell mehrere Homes? Dann müsste ich den Tibber-Collector noch erweitern, sodass man die ID angeben kann.

Der Tibber-Collector führt übrigens diese Query aus, um die Preise abzurufen:

```graphql
query {
    viewer {
      homes {
        currentSubscription{
          priceInfo{
            today {
              total
              startsAt
              level
            }
            tomorrow {
              total
              startsAt
              level
            }
          }
        }
      }
    }
  }
```

Du könntest im [Tibber API Explorer](https://developer.tibber.com/explorer) ausprobieren, ob das mit deinem Token eine sinnvolle Antwort ergibt.

**Comment by cjungde** [comment]
Danke, ich habe es gerade eingebaut.
Der Fehler "WARN[0000] The "TIBBER_INFLUX_MEASUREMENT" variable is not set. Defaulting to a blank string. " Ist jetzt weg.

Zum Token: Ich denke der Fehler liegt am lesen der .env Datei im tibber collector

Der Befehl gibt eine default variable aus:
`docker compose exec tibber-collector env`
`TIBBER_TOKEN=my-personal-tibber-token`

Das ist spannend, weil in der .env Datei ja auch Werte enthalten sind, die für den normalen Betrieb ausserhalb des Tibber collectors verwendet werden.

Ich habe den Token Wert natürlich in der .env überprüft und meinen eigenen Token auch auf der Tibberseite erfolgreich getestet.

**Comment by ledermann** [comment]
Die `.env` ist eine Sammlung aller Variablen, die für die verschiedensten Container von SOLECTRUS benötigt werden. Welche Variable wo verwendet wird, steht in der `compose.yaml` beim jeweiligen Service im Abschnitt `environment`.

Das falsche Tibber-Token `"my-personal-tibber-token"` wird einzig in der Dokumentation als Beispiel verwendet:
https://docs.solectrus.de/referenz/tibber-collector/konfiguration.html#beispielhafte-env

Entweder steht das bei dir immer noch in der `.env` (also anstelle des richtigen Tokens) **ODER** du hast den Container nach der letzten Änderung nicht neu gestartet. Dafür sollte ein `docker compose up -d` reichen, ggfs. vorher explizit die Container beenden (mit `docker compose down`, aber das sollte eigentlich nicht nötig sein).

Wenn es weiterhin nicht funktioniert, poste bitte mal deine `.env` (anonymisiert) und `compose.yaml`

**Comment by cjungde** [comment]
Jetzt funktioniert es !

Ich habe ein: 'docker compose down' und anschliessend ein 'docker compose up -d' gemacht.

'root@docker:~/solectrus# docker compose logs tibber-collector
tibber-collector-1  | Tibber collector for SOLECTRUS, Version 0.2.7, built at 2024-08-30T10:31:40.483Z
tibber-collector-1  | https://github.com/solectrus/tibber-collector
tibber-collector-1  | Copyright (c) 2023-2024 Georg Ledermann, released under the MIT License
tibber-collector-1  | 
tibber-collector-1  | Using Ruby 3.3.4 on platform x86_64-linux-musl
tibber-collector-1  | Pulling from https://api.tibber.com/v1-beta/gql every 3600 seconds
tibber-collector-1  | Pushing to InfluxDB at http://influxdb:8086, bucket solectrus, measurement my-prices
tibber-collector-1  | 
tibber-collector-1  | #1 - 2024-11-01 12:50:15 +0100
tibber-collector-1  |   Fetching prices from Tibber ... OK
tibber-collector-1  |   Pushing prices to InfluxDB ... OK
tibber-collector-1  |   Sleeping for 3600 seconds ...'

Danke für Deine Hilfe.
